// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size
// @generated from protobuf file "salesorder.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SalesOrder } from "./salesorder";
import type { NsoResponse } from "./salesorder";
import type { NsoRequest } from "./salesorder";
import type { GpdResponse } from "./salesorder";
import type { GpdRequest } from "./salesorder";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GpResponse } from "./salesorder";
import type { GpRequest } from "./salesorder";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service SalesOrder
 */
export interface ISalesOrderClient {
    /**
     * @generated from protobuf rpc: GetPricelist(GpRequest) returns (GpResponse);
     */
    getPricelist(input: GpRequest, options?: RpcOptions): UnaryCall<GpRequest, GpResponse>;
    /**
     * @generated from protobuf rpc: GetPricelistDetail(GpdRequest) returns (GpdResponse);
     */
    getPricelistDetail(input: GpdRequest, options?: RpcOptions): UnaryCall<GpdRequest, GpdResponse>;
    /**
     * @generated from protobuf rpc: NewOrder(NsoRequest) returns (NsoResponse);
     */
    newOrder(input: NsoRequest, options?: RpcOptions): UnaryCall<NsoRequest, NsoResponse>;
}
/**
 * @generated from protobuf service SalesOrder
 */
export class SalesOrderClient implements ISalesOrderClient, ServiceInfo {
    typeName = SalesOrder.typeName;
    methods = SalesOrder.methods;
    options = SalesOrder.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetPricelist(GpRequest) returns (GpResponse);
     */
    getPricelist(input: GpRequest, options?: RpcOptions): UnaryCall<GpRequest, GpResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GpRequest, GpResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPricelistDetail(GpdRequest) returns (GpdResponse);
     */
    getPricelistDetail(input: GpdRequest, options?: RpcOptions): UnaryCall<GpdRequest, GpdResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GpdRequest, GpdResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: NewOrder(NsoRequest) returns (NsoResponse);
     */
    newOrder(input: NsoRequest, options?: RpcOptions): UnaryCall<NsoRequest, NsoResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<NsoRequest, NsoResponse>("unary", this._transport, method, opt, input);
    }
}
